[package]
name = "mini_gl_fb"
version = "0.2.1"
authors = ["shivshank"]

[dependencies]
glutin = "0.17.0"
gl = "0.10.0"

[dependencies.rustic_gl]
git = "https://github.com/shivshank/rustic_gl.git"
rev = "f849057"
