[package]
name = "mini_gl_fb"
version = "0.4.0"
authors = ["shivshank"]
description = "Tool for quickly creating a window and drawing to a buffer with OpenGL"

license = "MIT"

keywords = ["OpenGL"]
repository = "https://github.com/shivshank/mini_gl_fb"

[dependencies]
glutin = "0.17.0"
gl = "0.10.0"
rustic_gl = "0.3.2"
